unique_ids:
  forms: {}
  modules:
    Form1: DKQWBH7MI4AFMMAHN7NRQM7DMUWCL2OY
    Form1.ItemTemplate1: 4PC3I4INBQPGU572CISFAZRO2QO4TQKF
    Form1.ItemTemplate1._template: BDTCC3TV7J6QOHN27K7QS7HOZLHB2UWY
    Form1._template: UV5FCSA45XCM3PSEUGT3CFDWCKPW4OQ3
  server_modules:
    ServerModule1: OA3LKS26EDOY43VVCH5JRLPE6ZFMZ65E
  assets:
    standard-page.html: VL6TASTVNW733CAWL66VSWVC4I6TDN63
    theme.css: YFTSO4PCINNUNIUZEE2JVYR4KVNXCJ6T
  scripts: {}
